In [6]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [7]:
from quantfin.market.assets import Stock
from quantfin.market.investment_universe import InvestmentUniverse

In [13]:
nas = InvestmentUniverse(name = "NASDAQ100")
nas_prices = nas.get_prices()

[*********************100%***********************]  101 of 101 completed

In [14]:
nas.prices

                  DDOG                                                 \
                  Open        High         Low       Close     Volume
Date
1962-01-02         NaN         NaN         NaN         NaN        NaN
1962-01-03         NaN         NaN         NaN         NaN        NaN
1962-01-04         NaN         NaN         NaN         NaN        NaN
1962-01-05         NaN         NaN         NaN         NaN        NaN
1962-01-08         NaN         NaN         NaN         NaN        NaN
...                ...         ...         ...         ...        ...
2022-01-05  152.449997  154.500000  144.729996  145.520004  7248100.0
2022-01-06  145.688995  151.339996  142.580002  143.889999  5939600.0
2022-01-07  144.000000  148.589996  140.589996  143.789993  2551800.0
2022-01-10  139.779999  146.520004  134.169998  146.330002  4952700.0
2022-01-11  144.800003  150.119995  143.500000  147.570007  1791615.0

                  OKTA                                                 ...  \
                  Open        High         Low       Close     Volume  ...
Date                                                                   ...
1962-01-02         NaN         NaN         NaN         NaN        NaN  ...
1962-01-03         NaN         NaN         NaN         NaN        NaN  ...
1962-01-04         NaN         NaN         NaN         NaN        NaN  ...
1962-01-05         NaN         NaN         NaN         NaN        NaN  ...
1962-01-08         NaN         NaN         NaN         NaN        NaN  ...
...                ...         ...         ...         ...        ...  ...
2022-01-05  208.110001  212.544998  197.639999  198.589996  2045900.0  ...
2022-01-06  197.649994  206.529999  192.750000  202.220001  2153900.0  ...
2022-01-07  199.559998  207.029999  195.949997  196.669998  1781200.0  ...
2022-01-10  189.059998  201.884995  184.020004  201.240005  2913300.0  ...
2022-01-11  198.610001  213.300003  197.460007  209.940002  1440245.0  ...

                  FISV                                                 \
                  Open        High         Low       Close     Volume
Date
1962-01-02         NaN         NaN         NaN         NaN        NaN
1962-01-03         NaN         NaN         NaN         NaN        NaN
1962-01-04         NaN         NaN         NaN         NaN        NaN
1962-01-05         NaN         NaN         NaN         NaN        NaN
1962-01-08         NaN         NaN         NaN         NaN        NaN
...                ...         ...         ...         ...        ...
2022-01-05  109.160004  110.599998  108.279999  108.360001  3762300.0
2022-01-06  108.160004  109.870003  107.639999  109.139999  2621500.0
2022-01-07  108.680000  109.980003  107.830002  108.830002  2687100.0
2022-01-10  108.089996  108.769997  104.410004  107.750000  3677200.0
2022-01-11  107.605003  109.464996  106.379997  109.110001  1200181.0

                   ADI
                  Open        High         Low       Close     Volume
Date
1962-01-02         NaN         NaN         NaN         NaN        NaN
1962-01-03         NaN         NaN         NaN         NaN        NaN
1962-01-04         NaN         NaN         NaN         NaN        NaN
1962-01-05         NaN         NaN         NaN         NaN        NaN
1962-01-08         NaN         NaN         NaN         NaN        NaN
...                ...         ...         ...         ...        ...
2022-01-05  175.320007  177.179993  172.729996  172.839996  3655200.0
2022-01-06  173.100006  174.960007  172.039993  173.389999  3584400.0
2022-01-07  173.100006  173.759995  166.000000  168.839996  6747500.0
2022-01-10  168.110001  170.729996  165.380005  170.399994  6012400.0
2022-01-11  168.770004  173.175003  168.460007  172.919998  1662089.0

[15113 rows x 505 columns]

In [25]:
sp = InvestmentUniverse(name = "SP500")
sp.get_prices()

[*********************100%***********************]  505 of 505 completed

2 Failed downloads:
- BRK.B: No data found, symbol may be delisted
- BF.B: None

                  QCOM                                                  \
                  Open        High         Low       Close   Adj Close
Date
1962-01-02         NaN         NaN         NaN         NaN         NaN
1962-01-03         NaN         NaN         NaN         NaN         NaN
1962-01-04         NaN         NaN         NaN         NaN         NaN
1962-01-05         NaN         NaN         NaN         NaN         NaN
1962-01-08         NaN         NaN         NaN         NaN         NaN
...                ...         ...         ...         ...         ...
2022-01-04  187.000000  188.929993  181.009995  187.229996  187.229996
2022-01-05  186.500000  193.580002  184.729996  186.500000  186.500000
2022-01-06  184.520004  188.470001  183.000000  185.949997  185.949997
2022-01-07  186.600006  188.360001  180.119995  180.410004  180.410004
2022-01-10  178.270004  179.037704  173.789993  175.339996  175.339996

                               PNC                                      ...  \
                Volume        Open        High         Low       Close  ...
Date                                                                    ...
1962-01-02         NaN         NaN         NaN         NaN         NaN  ...
1962-01-03         NaN         NaN         NaN         NaN         NaN  ...
1962-01-04         NaN         NaN         NaN         NaN         NaN  ...
1962-01-05         NaN         NaN         NaN         NaN         NaN  ...
1962-01-08         NaN         NaN         NaN         NaN         NaN  ...
...                ...         ...         ...         ...         ...  ...
2022-01-04   8484200.0  210.179993  218.839996  210.179993  215.889999  ...
2022-01-05  17141200.0  216.740005  218.360001  212.229996  212.389999  ...
2022-01-06   9117700.0  218.339996  220.690002  214.750000  220.570007  ...
2022-01-07   7381100.0  220.520004  224.520004  220.070007  223.729996  ...
2022-01-10   5919468.0  226.380005  226.389999  220.880005  221.119995  ...

                  ANTM                                            DUK  \
                   Low       Close   Adj Close     Volume        Open
Date
1962-01-02         NaN         NaN         NaN        NaN         NaN
1962-01-03         NaN         NaN         NaN        NaN         NaN
1962-01-04         NaN         NaN         NaN        NaN         NaN
1962-01-05         NaN         NaN         NaN        NaN         NaN
1962-01-08         NaN         NaN         NaN        NaN         NaN
...                ...         ...         ...        ...         ...
2022-01-04  457.570007  458.170013  458.170013   957300.0  103.360001
2022-01-05  458.049988  458.220001  458.220001   835300.0  103.500000
2022-01-06  432.970001  439.450012  439.450012  1763000.0  103.510002
2022-01-07  426.279999  434.989990  434.989990  1355400.0  102.809998
2022-01-10  430.829987  433.015015  433.015015   425575.0  104.650002


                  High         Low       Close   Adj Close     Volume
Date
1962-01-02         NaN         NaN         NaN         NaN        NaN
1962-01-03         NaN         NaN         NaN         NaN        NaN
1962-01-04         NaN         NaN         NaN         NaN        NaN
1962-01-05         NaN         NaN         NaN         NaN        NaN
1962-01-08         NaN         NaN         NaN         NaN        NaN
...                ...         ...         ...         ...        ...
2022-01-04  104.940002  103.279999  103.410004  103.410004  2558300.0
2022-01-05  104.919998  103.470001  103.639999  103.639999  2446600.0
2022-01-06  104.769997  103.330002  103.470001  103.470001  3944100.0
2022-01-07  104.970001  102.260002  104.500000  104.500000  2989900.0
2022-01-10  105.320000  104.070000  104.540001  104.540001  1242330.0

[15119 rows x 3030 columns]